### ISSUE TITLE
navagation and body are not sizing properly in IE

### ISSUE THREAD

**Issue by christopherpickering** [nasirkhan/mediawiki-bootstrap#10] opened 2016-03-11 19:16 UTC
Hi,
The navigation bars and body are not sizing properly in IE. Do you have a fix for that?

Thanks!
Christopher

**Comment by alistairmcmillan** [comment] 2016-04-10 15:00
Looks like a duplicate of #7

**Closed as completed** 2019-12-12 09:14 UTC
